hl.on("hyprland.start", function()
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("swaync")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("wl-clip-persist --clipboard regular")
	hl.exec_cmd("clipse -listen")
	hl.exec_cmd("otd-daemon")
	hl.exec_cmd("~/.config/waybar/scripts/launch_waybar.sh default.jsonc gray.css")
	hl.exec_cmd("mega-cmd")
	hl.exec_cmd("sleep 5 && rclone mount mega-webdav: ~/Cloud/Mega --vfs-cache-mode writes --vfs-cache-max-size 8G")
end)
