exec-once = systemctl --user start hyprpolkitagent
exec-once = swaync 
exec-once = hypridle
exec-once = wl-clip-persist --clipboard regular
exec-once = clipse -listen
exec-once = otd-daemon
exec = ~/.config/hypr/scripts/specific_configs.sh
exec = ~/.config/waybar/scripts/launch_waybar.sh default.jsonc gray.css
exec = hyprpaper
