hl.on("hyprland.start", function () 
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("swaync")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("hyprpaper")
  hl.exec_cmd("wl-clip-persist --clipboard regular")
  hl.exec_cmd("clipse -listen")
  hl.exec_cmd("otd-daemon")
  hl.exec_cmd("~/.config/hypr/scripts/specific_configs.sh")
  hl.exec_cmd("~/.config/waybar/scripts/launch_waybar.sh default.jsonc gray.css")
end)