background = 0xFF232323
base = 0xFF3D3D4D
text = 0xFFBCBCBC
accent = 0xFFEFEFFF

h1_size = 22
h2_size = 18
h3_size = 14
font_size = 12
small_font_size = 8
font_family = JetBrainsMono Nerd Font Propo
font_family_monospace = JetBrainsMono Nerd Font Propo

rounding_large = 6
rounding_small = 4
