# vim:ft=kitty

## name:     Catppuccin-Mocha
## author:   Pocco81 (https://github.com/Pocco81)
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #CDCDCD
background              #1E1E1E
selection_foreground    #1E1E1E
selection_background    #F5F5F5

# Cursor colors
cursor                  #F5F5F5
cursor_text_color       #1E1E1E

# URL underline color when hovering with mouse
url_color               #F5F5F5

# Kitty window border colors
active_border_color     #B4BEFE
inactive_border_color   #6C7086
bell_border_color       #F9E2AF

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #11111B
active_tab_background   #CBA6F7
inactive_tab_foreground #CDD6F4
inactive_tab_background #181825
tab_bar_background      #11111B

# Colors for marks (marked text in the terminal)
mark1_foreground #1E1E2E
mark1_background #B4BEFE
mark2_foreground #1E1E2E
mark2_background #CBA6F7
mark3_foreground #1E1E2E
mark3_background #74C7EC

# The 16 terminal colors

# black
color0 #454545
color8 #585858

# red
color1 #F38383
color9 #F38383

# green
color2  #A3E3A3
color10 #A3E3A3

# yellow
color3  #F9E2AF
color11 #F9E2AF

# blue
color4  #9999FA
color12 #9999FA

# magenta
color5  #F5C2E7
color13 #F5C2E7

# cyan
color6  #94E2D5
color14 #94E2D5

# white
color7  #C2C2C2
color15 #B6B6B6
