$black     = 0xff000000
$gray1     = 0xff1a1a1a
$gray2     = 0xff333333
$gray3     = 0xff4d4d4d
$gray4     = 0xff666666
$gray5     = 0xff808080
$gray6     = 0xff999999
$gray7     = 0xffb3b3b3
$gray8     = 0xffcccccc
$gray9     = 0xffe6e6e6
$white     = 0xffffffff
